del /S *.dsym
del /S *.o
del /S *.~*
del /S *.$$$
del /S *.dcu
del /S *.elf
del /S *.dpu
del /S *.dsk
del /S *.hpp
del /S *.ddp
del /S *.mps
del /S *.mpt
del /S *.map
del /S *.log
del /s *.exe
del /s *.so
del /s *.stat
del /s *.tci
rem del /s /A Thumbs.db